version: '2'

volumes:
  logs:
  hydra-db:
services:
  slim:
    image: php:7-alpine
    working_dir: /var/www
    command: php -S 0.0.0.0:8080 -t public
    environment:
      DEBUG: "true"
      docker: "true"
      HYDRA_HOST: 'http://hydra-server:4445'
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www
      - logs:/var/www/logs
  hydra-migrate:
    image: oryd/hydra:v1.0.0-beta.9-alpine
    links:
      - db
    environment:
      DATABASE_URL: mysql://root:pass@tcp(db:3306)/hydra?parseTime=true
    command:
      migrate sql -e
    restart: on-failure
  hydra-server:
    image: oryd/hydra:v1.0.0-beta.9-alpine
    links:
      - db
    depends_on:
      - hydra-migrate
    ports:
      # Public port
      - "8000:4444"
      # Admin port
      - "4445:4445"
      # Port for hydra token user
      - "5555:5555"
    command:
      serve all --dangerous-force-http
    environment:
      LOG_LEVEL: debug
      OAUTH2_ISSUER_URL: http://localhost:8000
      OAUTH2_CONSENT_URL: http://localhost:8080/consent
      OAUTH2_LOGIN_URL: http://localhost:8080/login
      DATABASE_URL: mysql://root:pass@tcp(db:3306)/hydra?parseTime=true
      SYSTEM_SECRET: youReallyNeedToChangeThis
      OAUTH2_SHARE_ERROR_DEBUG: 1
      OIDC_SUBJECT_TYPES_SUPPORTED: public,pairwise
      OIDC_SUBJECT_TYPE_PAIRWISE_SALT: youReallyNeedToChangeThis
    # OAUTH2_ACCESS_TOKEN_STRATEGY: jwt
    restart: unless-stopped
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: hydra
    volumes:
      - hydra-db:/var/lib/mysql
